#!/bin/bash

# Project Setup Script
# This script configures the monorepo for a new project by setting up environment variables
# and updating configuration files

set -e

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         PROJECT SETUP - Make This Repo Your Own               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will help you configure the monorepo for your project."
echo "It will prompt you for values and update all necessary files."
echo ""

# Function to prompt for a value with default
prompt_with_default() {
    local prompt_text=$1
    local default_value=$2
    local var_name=$3

    read -p "$prompt_text [$default_value]: " input_value
    if [ -z "$input_value" ]; then
        eval "$var_name='$default_value'"
    else
        eval "$var_name='$input_value'"
    fi
}

# Collect project information
echo "📝 Project Information"
echo "----------------------"
prompt_with_default "App Name (lowercase, no spaces, e.g., 'myapp')" "dottie" APP_NAME
prompt_with_default "App Display Name (e.g., 'My App')" "Dottie" APP_DISPLAY_NAME
prompt_with_default "GCP Project ID" "product-one-477118" GCP_PROJECT_ID
prompt_with_default "Firebase Project ID" "$GCP_PROJECT_ID" FIREBASE_PROJECT_ID
prompt_with_default "GCP Region" "us-central1" GCP_LOCATION
echo ""

# Derive other values
GCP_SERVICE_ACCOUNT="github-actions-cloudrun@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
GCP_ARTIFACT_REPOSITORY="${APP_NAME}-api-images"
API_URL_MAIN="https://${APP_NAME}-api-v7hdajoteq-nw.a.run.app"
WEB_URL_MAIN="https://${FIREBASE_PROJECT_ID}.web.app"
API_URL_BRANCH_PATTERN="https://api-{branch}.${FIREBASE_PROJECT_ID}.a.run.app"
WEB_URL_BRANCH_PATTERN="https://${FIREBASE_PROJECT_ID}--branch-{pr_number}-{hash}.web.app"
CORS_ORIGINS="https://${FIREBASE_PROJECT_ID}.web.app,https://${FIREBASE_PROJECT_ID}--*"
CLOUD_RUN_SERVICE_NAME_PATTERN="${APP_NAME}-api-{branch}"

echo "📋 Configuration Summary"
echo "------------------------"
echo "App Name: $APP_NAME"
echo "App Display Name: $APP_DISPLAY_NAME"
echo "GCP Project ID: $GCP_PROJECT_ID"
echo "Firebase Project ID: $FIREBASE_PROJECT_ID"
echo "GCP Region: $GCP_LOCATION"
echo ""
read -p "Does this look correct? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Setup cancelled. Run the script again to try with different values."
    exit 0
fi

# Create .env file
echo ""
echo "🔧 Creating root .env file..."
cat > .env << EOF
# ============================================
# PROJECT CONFIGURATION
# ============================================
# Generated by setup-project.sh on $(date)

# Project Identity
PROJECT_ID=$GCP_PROJECT_ID
APP_NAME=$APP_NAME
APP_DISPLAY_NAME=$APP_DISPLAY_NAME

# Firebase Configuration
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID

# GCP Configuration
GCP_PROJECT_ID=$GCP_PROJECT_ID
GCP_LOCATION=$GCP_LOCATION
GCP_SERVICE_ACCOUNT=$GCP_SERVICE_ACCOUNT
GCP_ARTIFACT_REPOSITORY=$GCP_ARTIFACT_REPOSITORY

# URLs - Production
API_URL_MAIN=$API_URL_MAIN
WEB_URL_MAIN=$WEB_URL_MAIN

# URLs - Branch Pattern (for CI/CD)
API_URL_BRANCH_PATTERN=$API_URL_BRANCH_PATTERN
WEB_URL_BRANCH_PATTERN=$WEB_URL_BRANCH_PATTERN

# Cloud Run Configuration
CLOUD_RUN_SERVICE_NAME_PATTERN=$CLOUD_RUN_SERVICE_NAME_PATTERN
CLOUD_RUN_REGION=$GCP_LOCATION

# CORS Origins (comma-separated)
CORS_ORIGINS=$CORS_ORIGINS

# Vite Environment Variables (for web app)
VITE_APP_NAME=$APP_NAME
VITE_APP_DISPLAY_NAME=$APP_DISPLAY_NAME
EOF

echo "✅ Created .env file"

# Update .firebaserc files
echo ""
echo "🔧 Updating Firebase configurations..."

cat > .firebaserc << EOF
{
  "projects": {
    "default": "$FIREBASE_PROJECT_ID"
  }
}
EOF
echo "✅ Updated .firebaserc"

cat > apps/web/.firebaserc << EOF
{"projects":{"default":"$FIREBASE_PROJECT_ID"}}
EOF
echo "✅ Updated apps/web/.firebaserc"

# Generate site.webmanifest
echo ""
echo "🔧 Generating PWA manifest..."
if [ -f "apps/web/public/favicon/site.webmanifest.template" ]; then
    sed "s/\${APP_DISPLAY_NAME}/$APP_DISPLAY_NAME/g" apps/web/public/favicon/site.webmanifest.template > apps/web/public/favicon/site.webmanifest
    echo "✅ Generated apps/web/public/favicon/site.webmanifest"
else
    cat > apps/web/public/favicon/site.webmanifest << EOF
{
  "name": "$APP_DISPLAY_NAME",
  "short_name": "$APP_DISPLAY_NAME",
  "icons": [
    {
      "src": "/web-app-manifest-192x192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "/web-app-manifest-512x512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "theme_color": "#ffffff",
  "background_color": "#ffffff",
  "display": "standalone"
}
EOF
    echo "✅ Created apps/web/public/favicon/site.webmanifest"
fi

# Update project-config.yml
echo ""
echo "🔧 Updating .github/project-config.yml..."
cat > .github/project-config.yml << EOF
# Project Configuration
# This file contains all project-specific variables used in GitHub Actions workflows
#
# Updated by setup-project.sh on $(date)

project:
  # Google Cloud Platform Configuration
  gcp:
    project_id: "$GCP_PROJECT_ID"
    region: "europe-west2"
    service_account: "$GCP_SERVICE_ACCOUNT"

    # Artifact Registry Configuration
    artifact_registry:
      repository: "$GCP_ARTIFACT_REPOSITORY"
      location: "europe-west2"

    # Cloud Run Configuration
    cloud_run:
      region: "europe-west2"
      memory: "512Mi"
      cpu: "1"
      min_instances: 0        # COST SAVINGS: Scale to zero when idle (prevents 24/7 charges)
      max_instances: 3        # COST CONTROL: Reduced from 10 to limit max concurrent instances
      timeout: "60s"
      concurrency: 100

  # Firebase Configuration
  firebase:
    project_id: "$FIREBASE_PROJECT_ID"
    hosting:
      main_url: "$WEB_URL_MAIN"
      branch_url_pattern: "$WEB_URL_BRANCH_PATTERN"

  # Application Configuration
  app:
    name: "$APP_NAME"
    api:
      entry_point: "apps/api"
      service_name_pattern: "$CLOUD_RUN_SERVICE_NAME_PATTERN"
      health_endpoint: "/api/health"
      cors_origins:
        - "$WEB_URL_MAIN"
        - "https://${FIREBASE_PROJECT_ID}--*.web.app"
      build_command: "npm install --production"
      test_command: "npm test"
      start_command: "npm start"

    web:
      entry_point: "apps/web"
      build_command: "npm run build"
      test_command: "npm test"
      dist_directory: "dist"
      environment_prefix: "VITE_"

# GitHub Secrets Used (for documentation)
# These secrets must be configured in your GitHub repository:
secrets:
  required:
    - GCP_SA_KEY                    # Google Cloud service account JSON key
    - GCP_PROJECT_ID                # Google Cloud project ID (should match project.gcp.project_id)
    - FIREBASE_SERVICE_ACCOUNT_KEY  # Firebase service account JSON key
    - FIREBASE_PROJECT_ID           # Firebase project ID
    - APP_NAME                      # Application name for branding
    - APP_DISPLAY_NAME              # Application display name
  optional:
    - GITHUB_TOKEN                  # Automatically provided by GitHub Actions
EOF
echo "✅ Updated .github/project-config.yml"

# Success message with next steps
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    ✅ SETUP COMPLETE!                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 Files Updated:"
echo "   • .env (root configuration)"
echo "   • .firebaserc (root and apps/web)"
echo "   • apps/web/public/favicon/site.webmanifest"
echo "   • .github/project-config.yml"
echo ""
echo "🚀 Next Steps:"
echo ""
echo "1. Set up GitHub Secrets (for CI/CD)"
echo "   Go to: Settings → Secrets and variables → Actions"
echo "   Add the following secrets:"
echo "   • GCP_SA_KEY: Your GCP service account JSON key"
echo "   • GCP_PROJECT_ID: $GCP_PROJECT_ID"
echo "   • FIREBASE_SERVICE_ACCOUNT_KEY: Your Firebase service account key"
echo "   • FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID"
echo "   • APP_NAME: $APP_NAME"
echo "   • APP_DISPLAY_NAME: $APP_DISPLAY_NAME"
echo ""
echo "2. Create API .env file"
echo "   The API needs its own .env with secrets (JWT, API keys, etc.)"
echo "   Copy from: apps/api/.env.example (if it exists)"
echo "   Or keep existing: apps/api/.env"
echo ""
echo "3. Install dependencies"
echo "   npm install"
echo ""
echo "4. Start development"
echo "   npm run dev"
echo ""
echo "💡 Tip: All these configuration values are now in .env"
echo "   Edit .env to change project settings, then re-run this script."
echo ""
